- raven/processes/ravenio.py
> absolute input file path. removed trailing /

- environment.yml
- raven/models/basic.py
- tests/common.py
- tests/test_basic.py
- tests/test_wps_gr4j_cemaneige.py
- tests/test_wps_raven_gr4j_cemaneige.py
- tests/test_wps_raven_hmets.py
Example of how the model output can be opened to compare results against actual known values. 
Let me know if something is missing.
> Added examples of tests looking into the data output files.

- raven/models/basic.py
- raven/models/cema_neige.py
- raven/models/gr4j_cemaneige.py
- raven/models/hbv.py
- raven/models/simhyd_cemaneige.py
- raven/processes/ravenio.py
- raven/processes/wps_gr4j_cemaneige.py
- tests/test_wps_caps.py
- tests/test_wps_gr4j_cemaneige.py
> Pep8 fixes

- .travis.yml
- Name for builds. 
- Separate build for PEP8.
> Travis tweak

- docs/source/developer.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/processes.rst
> updated process docs. added some notes on how to call Raven from Python

- raven/processes/__init__.py
- tests/test_wps_caps.py
Since data is lacking to make it functional.
> commented regionalization process

- Makefile
- raven/models/ostrich-gr4j-cemaneige/model/raven-gr4j-cemaneige.rvi
- raven/models/ostrich-hmets/model/raven-hmets-salmon.rvi
- raven/models/raven-gr4j-cemaneige/raven-gr4j-cemaneige.rvi
- raven/models/raven-hmets/raven-hmets.rvi
- raven/processes/wps_ostrich_gr4j_cemaneige.py
- raven/processes/wps_ostrich_hbv_ec.py
- raven/processes/wps_ostrich_hmets.py
- raven/processes/wps_ostrich_mohyse.py
- tests/test_base.py
- tests/test_emulators.py
- tests/test_wps_ostrich_gr4j_cemaneige.py
- tests/test_wps_ostrich_hmets.py
- tests/test_wps_raven_gr4j_cemaneige.py
- tests/test_wps_raven_hmets.py
- tests/testdata/ostrich-gr4j-cemaneige/raven-gr4j-salmon.rvi
- tests/testdata/ostrich-hmets/raven-hmets-salmon.rvi
- tests/testdata/raven-gr4j-cemaneige/raven-gr4j-salmon.rvi
- tests/testdata/raven-hmets/raven-hmets-salmon.rvi
PET is now calculated from the OUDIN formula instead of using user-generated PET for HMETS and GR4J
> Hardcoded PET formula for HMETS and GR4J

- raven/processes/wps_generic_zonal_stats.py
- tests/test_wps_generic_zonal_stats.py
Refactoring of zonal stats process.
> Simplied zonal stats and fixed bugs in response

- docs/source/notebooks/Delineation_workflow.ipynb
- raven/processes/wps_hydrobasins_shape_selection.py
Fix failure when lake is False and aggregate is True.
> lake must be True with aggregate_upstream

- raven/processes/wps_graph_ensemble_uncertainty.py
- raven/processes/wps_graph_single_hydrograph.py
This PR fixes #14 and adds support for NetCDF files for graph-making
> Few fixes for NETCDF support

- .readthedocs.yml
- .travis.yml
- Makefile
- docs/Makefile
- docs/source/notebooks/example_data.py
- docs/source/notebooks/index.rst
- requirements_dev.txt
- setup.py
This PR fixes #133 
Changes:
* Added a .readthedocs.yml configuration and docs requirements
> Fix raven docs

- .travis.yml
- docs/source/conf.py
- docs/source/notebooks/computing_objective_functions.ipynb
- requirements.txt
This PR is part of a combined effort to deal with #148 
Changes:
* Modified .travis.yml to make use of the Travis CI API
* Set sphinx to exclude Jupyter Notebook checkpoint files
* Added ipython to requirements.txt and IPython.sphinxext.ipython_console_highlighting to plugins
> Enabling jupyter notebooks to build with fewer errors

- Makefile
- environment.yml
- raven/utilities/graphs.py
- requirements.txt
- tests/test_base.py
- tests/test_emulators.py
- tests/test_wps_ostrich_hbv_ec.py
- tests/test_wps_raven_hbv_ec.py
Update Raven. Fixes issue with LinearTransform not being applied to 1D gauge data. 
HBV-EC returns different diagnostic results.
> Update raven to version to 2.9.2 (rev240)

- CHANGES.rst
- raven/models/base.py
- raven/models/rv.py
- raven/processes/wps_hydrobasins_shape_selection.py
- tests/test_emulators.py
- tests/test_rv.py
This PR fixes #209 
Changes:
* Modified tag
* Modified tests
* Do not write empty zip files
Not obvious in the test suite that there is a speed up.
> Add :DontWriteWatershedStorage when suppress_output is True

- .gitignore
- Makefile
- raven/models/emulators.py
- raven/models/ostrich-mohyse/ostIn.txt
- raven/models/raven-mohyse/raven-mohyse.rvh
- raven/models/rv.py
- raven/processes/wps_ostrich_mohyse.py
- raven/processes/wps_raven_mohyse.py
- raven/processes/wps_raven_multi_model.py
- tests/test_ERA5.py
- tests/test_base.py
- tests/test_emulators.py
- tests/test_rv.py
- tests/test_wps_ostrich_gr4j_cemaneige.py
- tests/test_wps_ostrich_hmets.py
- tests/test_wps_ostrich_mohyse.py
- tests/test_wps_raven_gr4j_cemaneige.py
- tests/test_wps_raven_hmets.py
- tests/test_wps_raven_mohyse.py
This PR fixes #222, #145
Changes:
* Raven version is now 254
To rebuild: 
```
make raven_clean
make raven_dev
```
Lots of failing tests... need to understand what changed. 
> Update Raven version [WIP]

- tests/test_NRCAN_daily.py
Added a test that uses NRCAN data for a catchment, for ncml and usage info.
> Added tests and codes to integrate NRCAN ncml datasets.

- docs/source/notebooks/gridded_data_subset.ipynb
Improved the gridded_data_subset notebook:
Added comments
Fixed ERA5 precipitation linear transform
Removed addition of 00:00:00 timestamp on netcdf files
Tested other models
Added RAVEN output netcdf file download method
> Add comments and adjust ERA5 scale in gridded data notebook

- raven/processes/wpsio.py
> added wpsio nc_index abstract

- .cruft.json
- requirements_dev.txt
- setup.cfg
To get changes from this cookiecutter PR https://github.com/bird-house/cookiecutter-birdhouse/pull/87
> Refresh cookiecutter template

- .travis.yml
- environment.yml
- raven/processes/wps_q_stats.py
- requirements.txt
This PR fixes #280 
Changes:
* Adjusted some calls to metadata formatting functions
* Adjusted dependencies to be more in line with those of xclim
> Update a few calls and adjust dependencies to new xclim calls

- environment.yml
- raven/models/base.py
- raven/models/rv.py
- raven/processes/wps_q_stats.py
- raven/utilities/graphs.py
- requirements.txt
- setup.py
- tests/conftest.py
This PR partially fixes #286 
Changes:
* Pin xarray==0.16
* Pin xclim==0.18
> Update version of xarray and xclim

- CHANGES.rst
- Makefile
- raven/models/base.py
- raven/models/global/global.rvc
- raven/models/rv.py
- tests/test_emulators.py
This PR fixes #275 
Changes:
* Modified version in config file to 3.0
* Remove scale_factor and add_offset handling since it's taken care of by the executable.
> Update Raven to 3.0

- docs/source/notebooks/gridded_data_subset.ipynb
- raven/models/base.py
- raven/models/raven-gr4j-cemaneige/raven-gr4j-cemaneige.rvi
- raven/models/raven-hbv-ec/raven-hbv-ec.rvi
- raven/models/raven-hmets/raven-hmets.rvi
- raven/models/raven-mohyse/raven-mohyse.rvi
- raven/models/rv.py
- tests/test_bias_correction.py
- tests/test_emulators.py
This PR fixes #300 
Changes:
* Added `calendar` property in RVI class
* Detect `calendar` from netcdf files
* Write calendar into RVI templates for all four emulators. 
** Needs to be tested with forcing using non-standard calendars before merging **
> Add support for non-standard calendars. requires testing

- Makefile
- raven/models/rv.py
- tests/test_emulators.py
> Update Raven to 3.0.1

- .travis.yml
- Makefile
This PR fixes #312 
Changes:
* Removed `pep8` makefile recipe (duplicate of `lint`)
* Disabled doc-build stage iin Travis-CI configuration
> Disable the docs stage on travis-ci

- CHANGES.rst
- raven/models/base.py
- raven/models/rv.py
- tests/test_emulators.py
- tests/test_rv.py
This PR fixes #319 
Changes:
* Added `:Deaccumulate` option to RVT template.
> add deaccumulate option

- raven/tutorial.py
This PR fixes #327 
Changes:
* Added a check that deletes the downloaded file if an accompanying md5 is not found.
> Unlink files that do not have an accompanying md5

- CHANGES.rst
- raven/processes/__init__.py
- raven/processes/wps_graph_forecast_uncertainty.py
- raven/utilities/graphs.py
- tests/test_wps_forecast_graphs.py
Resolves #237 and #238 .
Updated:
- graphs utilities
- __init__ for wps process
Added:
- wps for forecast and hindcast graphics
- test suite for forecast and hindcast graphics
> complete WPS and test suite for forecast/hindcast uncertainty graphics 

- docker-compose.yml
Very small PR, read the 2 short commit descriptions.
> Make docker-compose run tests generic and reproducible

- docs/source/notebooks/Comparing_hindcasts_and_ESP_forecasts.ipynb
- raven/processes/wps_climatology_esp.py
- tests/common.py
Changes:
* Fix wrong acronym (my fault)
> replaced ensemble by extended

- .github/workflows/main.yml
> Enable GitHub CI

- Makefile
Fix the wrong output file path and not replacing the output url properly with the refresh target.  See commit description for details.
https://github.com/Ouranosinc/raven/pull/393#issuecomment-860952912
> Fix broken refresh target

- docs/source/installation.rst
This PR fixes #182 
Changes:
* Added installation methods for building from source and for installing from conda-forge
This entire approach was tested on an Ubuntu 20.04 VM. Everything works perfectly according to these steps.
> Modern installation documentation

- .zenodo.json
Fix for PR https://github.com/Ouranosinc/raven/pull/442
> Fix my zenodo name

- .github/workflows/main.yml
Changes:
* Used a workaround to fix a CI action
https://github.com/conda-incubator/setup-miniconda/issues/274
> use mambaforge workaround

- .zenodo.json
Changes:
* Added `ouranos` Zenodo community
> Add ouranos Zenodo community

- .github/workflows/docker-testing.yml
- .github/workflows/main.yml
- README.rst
* Added custom endpoints for security in `main.yml`
* Now using commit hashes for specifying action versions
I think `raven` will be ready for release after this PR
> Update security checks
