Makefile
raven/models/raven-gr4j-cemaneige/raven-gr4j-cemaneige.rvi
raven/models/raven-hbv-ec/raven-hbv-ec.rvi
raven/models/raven-hmets/raven-hmets.rvi
raven/models/raven-mohyse/raven-mohyse.rvi
raven/models/rv.py
tests/test_emulators.py

Adds global netcdf attributes to output files, include the `model_id` attribute. 
Note that comments with commas or spaces are chopped, so only the first word is saved. Not a big issue for now, but something to consider.

Added global netcdf attributes 

---

Makefile
raven/models/base.py
raven/processes/wps_raven_hmets.py
tests/test_base.py
tests/test_emulators.py
tests/test_rv.py

Failing tests on master were due to unfinished implementation of random seed refactor, and the hmets identifier - _ switch. 
In principle, all tests should pass locally, we now need to make sure they pass on Travis-CI as well.

Clean up failing tests

---

.dockerignore
.gitignore
Dockerfile
MANIFEST.in

Many small changes to get the docker image to build, then to probably run against the various notebooks under docs/source/notebooks.
I said probably because none of the notebooks are working yet but all the errors look like configuration errors and not runtime errors anymore.
I am sending a PR even though the work is not fully tested because I need to pause and work on different issue.
Read commit messages for more info, especially the "docker: set LD_LIBRARY_PATH to find libnetcdf.so.13"
Changes:
* All relevant fixes are in the Dockerfile, not touching any code.
* Docker hub has been configured to build this Dockerfile, see https://hub.docker.com/r/pavics/raven

Fix docker image to build and to be able to probably run the service

---

.readthedocs.yml
docs/source/conf.py
environment-docs.yml
environment.yml
raven/__init__.py

This PR fixes #148.  No need to use Github pages anymore.
Working doc build with autodoc: https://pavics-raven.readthedocs.io/en/fix-rtd-build-with-smaller-env-yml/processes.html
Changes:
* New `environment-docs.yml` with minimal package install required to be used when building docs on ReadTheDocs so we do not burst the memory limit.
* Mock import all the 3rd party dependency packages (xarray, numpy, ...) so these dependencies are not needed to be installed to not burst the memory limit.
* Raven source is added to sys.path so it can be "crawled" by autodoc without being installed.
* Migrated .readthedocs.yml config file to v2 format, not sure if it helped with the memory limitation but v2 is currently the latest version and we seem to be using v1.
* New …

Get ReadTheDocs build to work without bursting memory limit when using sphinx autodoc

---

environment.yml
requirements.txt

conda env: add psycopg2 to be able to use Postgres to log pywps requests in Prod
When the following config is used when running the docker image:
[logging]
level = INFO
database=postgresql://user:pass@postgres/raven
"psycopg2" technically is only needed for production deployment so
potentially be added via individual `conda install` inside `Dockerfile`
instead.  I choose to add it to `environment.yml` so that during
dev/testing, we can also replicate "production environment".
It's always a best practice that dev/test environment mirror as much as
possible the production environment to smoke out all the relevant bugs.
PR https://github.com/Ouranosinc/PAVICS/pull/173 had to disable Postgres for Raven because of this missing library.

conda env: add psycopg2 to be able to use Postgres to log pywps requests in Prod

---

docs/source/notebooks/Region_selection.ipynb
docs/source/notebooks/Run_Raven_with_Parallel_parameters.ipynb
docs/source/notebooks/getting_variables_other_than_flow.ipynb
docs/source/notebooks/multi_model_simulation.ipynb
docs/source/notebooks/running_OSTRICH_gr4jcn.ipynb

This PR fixes the notebooks so more are passing on Jenkins (still not all are passing).
Jenkins run: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/enable-raven-notebooks-in-jenkins/14/console
I think, not fully sure, that the only 3 root cause failure are:
* `progress=True`, need to somehow wait for it to finish or not use it
* ipyleaflet notebooks needs a default selection because there are no interactive user to make the selection (this is the one I am not sure)
* `Raven_run_parallel_basins.ipynb` failing with some broken pipe
Edit:
* add 3rd reason

Fix notebooks for jenkins automated testing

---

.travis.yml

This PR fixes #203 
Changes:
* Added a Travis CI build to explicitly test the notebooks and is allowed to fail.

Pytest for notebooks in allowed_fail build

---

.readthedocs.yml
.travis.yml
Makefile
docs/source/output_sanitize.cfg
environment-docs.yml
environment.yml
requirements.txt
tests/common.py

Fixes #220 
It appears that the `latest` version of the ReadTheDocs build image raises errors due to excessive memory consumption. This is triggered no matter what is configured in the `environment_docs.yml` leading me to assume that there are issues with the build or how memory is configured for the VMs on their server.
I have tried performing the same operations using their `build:latest` docker image and no problems to be had. As a result, I'm defaulting the build to use the `build:stable` release.

Use the stable ReadTheDocs build image

---

.travis.yml

Fix this error on TravisCI:
MaxRetryError: HTTPConnectionPool(host='localhost', port=8093): Max retries exceeded with url: /?service=WPS&request=GetCapabilities&version=1.0.0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3846780668>: Failed to establish a new connection: [Errno 111] Connection refused',))
Related to PR https://github.com/Ouranosinc/raven/pull/271

.travis.yml: set FLYINGPIGEON_WPS_URL to the production one because we do not launch a local FP on TravisCI build

---

environment.yml

Else `make develop` fail to install the newer `gdal` using `pip` (compile error below).
`gdal` was updated in `requirements.txt` in this commit 0c57bb47.
```
gcc -pthread -B /home/lvu/.conda/envs/raven/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../og
r/ogrsf_frmts -I../../gnm -I../../apps -I/home/lvu/.conda/envs/raven/include/python3.7m -I/home/lvu/.conda/envs/raven/lib/python3.7/site-packages/numpy/core/include -I/home/lvu/.conda/envs/raven/include -c exten
sions/gdal_wrap.cpp -o build/temp.linux-x86_64-3.7/extensions/gdal_wrap.o -I/home/lvu/.conda/envs/raven/include
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ …
```

environment.yml: sync gdal version with requirements.txt

---

raven/tutorial.py

This PR fixes #327 (again)
Changes:
* Added branch name (default: `master`) to the filepath of cached files

ensure branch name is preserved in filepath

---

tests/common.py
tests/conftest.py
tests/test_ERA5.py

This PR speeds up the ERA test. It downloads test data from raven-testdata and caches it locally. The test uses the local cache instead of downloading the data every time.

Test era from cache

---

environment.yml

This PR fixes #332 
Changes:
* Added `tbb` to the environment.yml 
`libtbb` seems to be a system-level library that not all systems come installed with. Adding it here prevents GDAL from crashing with certain imports.
https://github.com/oneapi-src/oneTBB

add Thread Building Blocks library to environment.yml

---

Makefile

The syntax in `environment.yml` and `requirements.txt` do not allow specifying pip options for ravenpy and old `raven_dev`, `ostrich_dev` make target not working anymore.
To fix `make test-notebooks` errors;
```
docs/source/notebooks/Climatological_ESP_forecasting::ipynb::Cell 1 Traceback (most recent call last):                                                                                                               File "/home/lvu/.conda/envs/raven/lib/python3.7/site-packages/pywps/app/Process.py", line 249, in _run_process
self.handler(wps_request, wps_response)  # the user must update the wps_response.                                                                                                                                File …
```

Makefile: work-around to install ravenpy with binaries

---

requirements_dev.txt

`make test-notebooks` error:
```
________________________________________________________________________ docs/source/notebooks/Bias_correcting_climate_data.ipynb::Cell 3 _________________________________________________________________________
Notebook cell execution failed
Cell 3: Cell execution caused an exception
Input:
import nc_time_axis
import cftime
group_month_nowindow = sdba.utils.Grouper('time.month')
Adj = sdba.DetrendedQuantileMapping(nquantiles=50, kind='+', group=group_month_nowindow)
Adj.train(ds_ref_sub['pr'],ds_his_sub['pr'])
Scen_pr = Adj.adjust(ds_fut_sub['pr'], interp="linear")
Adj.train(ds_ref_sub['tasmax'],ds_his_sub['tasmax'])
Scen_tasmax = Adj.adjust(ds_fut_sub['tasmax'], interp="linear")
Adj.train(ds_ref_sub['tasmin'],ds_his_sub['tasmin'])
Scen_tasmin = …
```

requirements_dev.txt: notebook tests require package nc-time-axis

---

environment.yml

OWSLib timeout bug https://github.com/geopython/OWSLib/issues/737

pin owslib to 0.21 to avoid timeout bug in 0.22

---

Dockerfile
environment.yml
requirements.txt

This PR addresses the docker image build issues by relying on the conda-sourced binaries for `ravenc`, `ostrich`, and `RavenPy`.
Changes:
* Simplified the dockerfile install steps for `raven-wps`
* Now using the binaries for `ravenc`, `ostrich`, and `RavenPy` currently hosted on `zeitsperre`

Use the zeitsperre anaconda source for the ravenpy dependencies

---

Dockerfile

With 3.7, it starts on my VM lvupavicsdev.ouranos.ca (available for testing).
Docker image do not start under python 3.8 with this error:
```
Traceback (most recent call last):
File "/opt/conda/envs/wps/bin/raven-wps", line 33, in <module>
sys.exit(load_entry_point('raven', 'console_scripts', 'raven-wps')())
File "/opt/conda/envs/wps/bin/raven-wps", line 25, in importlib_load_entry_point
return next(matches).load()
File "/opt/conda/envs/wps/lib/python3.8/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/opt/conda/envs/wps/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", …
```

docker: pin python 3.7 instead of 3.8, try to fix image do not start

---

raven/processes/wps_raven.py
tests/test_wps_raven_gr4j_cemaneige.py

Following up from https://github.com/CSHS-CWRA/RavenPy/pull/98, add a friendlier error message to the server response (if you accept the fact that an entire stacktrace is something friendly).

Use ProcessError in RavenProcess._handler

---

Makefile
docs/source/dev_guide.rst

It is always a pain to catch up on notebooks development (making them work) at the last minute, as we just have seen with PR https://github.com/Ouranosinc/raven/pull/374 (`make start` not up-to-date with newer RavenPy conda package, breaking `make test-notebooks` and `make refresh-notebooks`, then the notebook automated testing `make test-notebooks` did not like that the cell number was stripped from notebooks).
For users not developping in this repo often, they also need a reminder what is the procedure to properly re-create a fresh environment for development.
This PR is meant to clarify the notebooks dev workflow so we can all be on the same page and all use the same process so if the process needs update, we can all benefit instead of each person finding work-around for their own …

Update dev workflow documentation related to notebooks development and testing

---

environment.yml
requirements.txt

Xclim 0.29.0 introduced a breaking API change for SDBA objects. This temporarily pins xclim below this change.

Pin Xclim below 0.29.0

---

Makefile

Makefile updated for future refresh.
See PR https://github.com/bird-house/birdhouse-deploy/pull/203
Not refreshing the notebooks because they do not all work in Jenkins yet and are not enabled in Jenkins by default.

Makefile update for wpsoutputs path change to bird name

---

Dockerfile
environment-docs.yml
environment.yml
requirements.txt

Changes:
* Updated base to Python3.8
* Updated docker image to use `condaforge/mambaforge` and mamba
* Set Debian/Ubuntu image frontend settings to `"noninteractive"`

Fix Raven Docker Image, pin Pandas below v2.0

---

CHANGES.rst

This prepares a new release with the updated ReadMe and removed HPC interface.
The current build of Raven-WPS on conda pins `pandas` below v2.0. This can cause problems for the `conda` solver and needs to be updated anyway.

Prepare v0.18.1

---

.github/workflows/docker-testing.yml
.github/workflows/main.yml
CHANGES.rst
Dockerfile
Makefile

Changes:
* Added a workflow that uses a docker image to test RavenWPS
* Modified Dockerfile to no longer emit warnings on build.
* Standardized recipe with other project conventions.
* Fixed a bug in the Makefile that was calling `ifdef` in `make` land and not within `shell` land

Add a docker-based testing suite

---

docs/source/conf.py
environment.yml
pyproject.toml
raven/processes/base_xclim.py

This PR fixes [issue id]
Changes:
* Replaced `unidecode` (GPLv2) with `anyascii` (MIT)
* Removed `pandoc`, `poppler`, and `tbb` from conda environment dependencies
There are still some final issues with the licensing for `cartopy` which changed from LGPL to BSD-3-Clause in version 0.23. This update will force us to drop Python3.8. I'll address this in a new Pull Request.

Remove unidecode (for anyascii), pandoc, poppler, and tbb

---

.github/workflows/main.yml

This PR closes #498 
Changes:
* Added concurrency for cancelling older builds when new commits are pushed to a branch
* Add the step-security/harden-runner action to `main` workflow

Use concurrency in workflows

---

.github/workflows/main.yml

Changes:
* Makes it so that `pip check` failures do not fail CI builds.

Do not fail on pip check

---

.github/workflows/main.yml
.pre-commit-config.yaml

Changes:
* Added some logic to skip lint checks on `main` (some hooks fail when run on `main` by design)
* Always run `conda` step on pushes to `main` but run it dependent on `lint` in pull requests.
* Update `pre-commit` hooks

Fixup lint check configuration
